name: SpritesheetPacker

on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Run QMake
      run: qmake sprite-sheet-packer.pro

    - name: Build
      run: |
        make -j8

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SpriteSheetPacker-macos
        path: |
          ./*.dmg
          ./**/*.dmg

  linux:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Download linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        mkdir -p $GITHUB_WORKSPACE/bin
        mv linuxdeployqt-continuous-x86_64.AppImage $GITHUB_WORKSPACE/bin/linuxdeployqt
        chmod +x $GITHUB_WORKSPACE/bin/linuxdeployqt
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        sudo apt-get install -y libxcb-composite0 libxcb-damage0 libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xevie0 libxcb-xf86dri0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcb-xprint0 libxcb-xtest0 libxcb-xv0 libxcb-xvmc0

    - name: Run QMake
      run: qmake sprite-sheet-packer.pro

    - name: Create AppDir
      run: |
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/lib
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        cp install/linux/SpriteSheetPacker.desktop AppDir/usr/share/applications/
        cp SpriteSheetPacker/res/icon.png AppDir/usr/share/icons/hicolor/256x256/apps/SpriteSheetPacker.png
        cp -r SpriteSheetPacker/defaultFormats AppDir/usr/bin/

    - name: Build
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/SpriteSheetPacker/3rdparty/PVRTexTool/Linux_x86_64
        make -j8

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SpriteSheetPacker-linux
        path: |
          ./*.AppImage
          ./**/*.AppImage
